on: push
name: Deploy the static Storybook
jobs:
  storybook-deploy:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
    - name: build docs
      run: npm run build:docs
      
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.alacerte.devwebgarneau.com
        username: alacerte
        password: ${{ secrets.FTP_PASSWORD }}
        
        local_path: ./storybook-static
        remote_path: ./public_html/tp1-storybook
